"""Core research logic — orchestrates fetching, SQLite caching, and LLM synthesis."""

from __future__ import annotations

import json
import logging
from pathlib import Path

from ai.schemas import AnswerWithCitations, Source
from src.concurrency.orchestrator import fetch_all
from src.config import settings
from src.services.ai_service import AIService
from src.services.cache import QueryCache
from src.services.tracing import get_tracer
from src.storage.cache_store import CacheStore
from opentelemetry.trace import Tracer

logger = logging.getLogger(__name__)


def _source_matches_cache_key(source: Source, cache_key: str) -> bool:
    if cache_key == "wiki":
        return source.origin == "wikipedia"
    return source.origin == cache_key


async def research(
    question: str,
    *,
    sources: tuple[str, ...] = ("wiki", "arxiv", "web"),
    no_cache: bool = False,
    tracer: Tracer | None = None,
) -> AnswerWithCitations:
    """Run the full research pipeline for a question.

    Checks SQLite cache for individual sources first. Any misses are fetched
    in parallel and cached. The final answer is generated by a retrying LLM
    service, and its cost is logged to the telemetry database.
    """
    if not question.strip():
        raise ValueError("question must be non-empty")

    tracer = tracer or get_tracer(__name__)
    logger.info("research_start", extra={"question": question, "sources": sources})

    with tracer.start_as_current_span("research.request") as span:
        span.set_attribute("research.question", question)
        span.set_attribute("research.sources_requested", ",".join(sources))
        span.set_attribute("research.no_cache", no_cache)

        # 1. Initialize persistent services
        db_dir = Path(settings.cache_dir)
        db_dir.mkdir(parents=True, exist_ok=True)
        db_path = db_dir / "cache.db"

        # Open connection via Context Manager / direct instance
        store = CacheStore(db_path=db_path)
        cache = QueryCache(store=store, ttl_seconds=settings.cache_ttl_seconds)
        svc = AIService(
            max_parallel=settings.max_parallel,
            source_timeout_seconds=settings.per_source_timeout_seconds,
            synthesize_timeout_seconds=30.0,
            tracer=tracer,
        )

        fetched_sources: list[Source] = []
        sources_to_query: list[str] = []

        try:
            # 2. Check cache first for each source (unless no_cache is active)
            for src in sources:
                if no_cache:
                    sources_to_query.append(src)
                else:
                    cached_result = cache.get(src, question)
                    if cached_result:
                        try:
                            cached_list = json.loads(cached_result.response_json)
                            deserialized = [Source(**item) for item in cached_list]
                            fetched_sources.extend(deserialized)
                            logger.info("pipeline_cache_hit", extra={"source": src, "count": len(deserialized)})
                        except Exception as exc:
                            logger.warning("pipeline_cache_corrupted", extra={"source": src, "error": str(exc)})
                            sources_to_query.append(src)
                    else:
                        sources_to_query.append(src)

            # 3. Query the missed sources concurrently
            if sources_to_query:
                logger.info("pipeline_fetching_misses", extra={"sources": sources_to_query})
                new_sources, timings = await fetch_all(question, sources=sources_to_query, ai_service=svc)

                # Update cache for each query origin
                for src in sources_to_query:
                    src_list = [s for s in new_sources if _source_matches_cache_key(s, src)]
                    serialized = json.dumps([s.model_dump() for s in src_list])
                    cache.set(src, question, serialized)

                fetched_sources.extend(new_sources)
                logger.info("pipeline_fetched", extra={"new_sources": len(new_sources), "timings": timings})

            if not fetched_sources:
                raise RuntimeError("All sources failed or returned no results. Synthesis cannot proceed.")

            # 4. Synthesize final answer using the retry service
            logger.info("pipeline_synthesize_start", extra={"total_sources": len(fetched_sources)})
            answer = await svc.synthesize(question, fetched_sources)

            # 5. Calculate & Record Cost Telemetry (Input/Output token approximation)
            # Gemini 2.0 Flash pricing: $0.075 / 1M input tokens, $0.30 / 1M output tokens
            # Standard SE rule of thumb: 1 token ~= 4 characters
            input_text = question + "\n".join(s.snippet for s in fetched_sources)
            output_text = answer.answer
            input_tokens = len(input_text) / 4.0
            output_tokens = len(output_text) / 4.0
            cost_usd = (input_tokens * (0.075 / 1_000_000)) + (output_tokens * (0.30 / 1_000_000))

            # Record spend under "synthesis" provider
            store.record_spend("synthesis", cache.canonicalize_query(question), cost_usd)
            logger.info("pipeline_done", extra={"citations": len(answer.citations), "cost_usd": round(cost_usd, 6)})
            span.set_attribute("research.total_sources", len(fetched_sources))
            span.set_attribute("research.cost_usd", round(cost_usd, 6))

            return answer

        finally:
            store.close()
